src/components/views/HomePageView.js
=> Fixed error

src/components/containers/NewStudentContainer.js
=> Add New Student

src/App.js, src/components/containers/EditStudentContainer.js, src/components/containers/StudentContainer.js, src/components/containers/index.js, src/components/views/EditStudentView.js, src/components/views/StudentView.js, src/components/views/index.js, src/store/thunks.js
Added EditStudentsContainer, EditStudentView, altered editStudentThunk, and created edit student route.
=> Edit Student Functionality

src/components/containers/NewStudentContainer.js
fixed add student so it doens't allow invalid campus id
=> Add student function

src/components/views/StudentView.js, src/components/views/css/StudentView.css
Added styling to student view and added an unroll button.
=> Student Page View

src/components/containers/EditStudentContainer.js, src/store/thunks.js
Show an alert if a user inputs an invalid campusID when editing a student.
=> Validating campusID in Edit Student

src/components/containers/EditStudentContainer.js, src/components/containers/StudentContainer.js, src/components/views/StudentView.js
Added implementation for unenrolling a student from a campus in the Student View and added comments to Edit Student.
=> Added unenrollment implementation

src/App.js, src/components/containers/NewCampusContainer.js, src/components/containers/index.js, src/components/views/AllCampusesView.js, src/components/views/NewCampusView.js, src/components/views/index.js, src/store/actions/actionCreators.js, src/store/actions/actionTypes.js, src/store/reducers/campuses.js, src/store/thunks.js
- Added container and view files for adding a new campus
- Added a component to display an add new campus form (ensured valid inputs are passed and styling matches requirements)
- New campus added to the database and in the All Campuses list without refreshing
- Updating other files to support this new addition
=> Added functionality for adding a new campus

src/components/containers/NewCampusContainer.js, src/components/views/AllCampusesView.js, src/components/views/NewCampusView.js, src/components/views/css/AllCampusesView.css
- Updated styling of all the campuses and the add a new campus button
- Added minor changes to overall functionality
=> Updated all campuses and a new campus

src/components/views/CampusView.js, src/components/views/css/CampusView.css
- Updates campus pages with image url saved in database
- Adds framework for editing campus and deleting campus through buttons
=> Updates single campus page

src/App.js, src/components/containers/CampusContainer.js, src/components/containers/EditCampusContainer.js, src/components/views/CampusView.js, src/components/views/EditCampusView.js, src/store/actions/actionCreators.js, src/store/actions/actionTypes.js, src/store/reducers/campuses.js, src/store/thunks.js
- Adds campus editing actions and reducer in Redux Store
- Adds components used to edit campus information
=> Functionality for Editing Campuses

src/components/containers/AllCampusesContainer.js, src/components/views/AllCampusesView.js, src/components/views/CampusView.js, src/store/actions/actionCreators.js, src/store/actions/actionTypes.js, src/store/reducers/campuses.js, src/store/thunks.js
- Adds a button to delete campus in all campus view
- Removes delete campus button from single campus view
- Adds deleting campus action and reducer to Redux Store
=> Campus Deleting Functionality

src/components/containers/CampusContainer.js, src/components/views/CampusView.js, src/components/views/css/CampusView.css
- Allows students to be unenrolled from their respective campus page
- Requires styling changes for the student information section
- Adds default header when no students are enrolled in a campus
=> Students Unenrollment

src/components/containers/EditCampusContainer.js, src/components/views/CampusView.js
- Resolves error occuring during campus editing
=> Resolves Edit Campus Error

src/components/containers/NewCampusContainer.js
- Fixed the display of the campus image for new campuses being added
=> Default image for new campuses

src/components/views/CampusView.js
- Adds information on total number of students enrolled
=> Enrollment Counter for Campuses

src/components/views/AllStudentsView.js, src/components/views/EditStudentView.js, src/components/views/StudentView.js, src/components/views/css/AllStudentsView.css
- Added styling changes to the edit student form and viewing a single student
- Added a white box around all the students
- Changed the style of all the buttons in the students section
=> Minor changes to student

src/components/views/EditCampusView.js, src/components/views/NewCampusView.js
- Updated adding a new campus form to include asterisks for required information
- Fixed description of editing a campus to start from the top of the box
=> Updated campus views

src/components/views/EditStudentView.js, src/components/views/HomePageView.js, src/components/views/NewStudentView.js, src/components/views/StudentView.js
- Adds original students name to edit form header
- Fixes majority of compilation warnings from student related components
=> Initial student name in editing form

src/components/views/EditCampusView.js
- Adds original campus name to campus editing forms title
=> Update Campus Edit Form
